name: "Final-Success-Build"
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # لدعم ملفات الـ Zip الكبيرة التي رأيناها

      - name: Godot Android Export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
          # السيرفر سيبحث الآن بجانب ملف project.godot مباشرة
          relative_project_path: "./"
          archive_output: true
          # هذا التعديل يحل مشكلة Warning: Unexpected input في صورتك الأخيرة
          presets_to_export: "Android" 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sapphire-Hero-Game
          path: /home/runner/.local/share/godot/archives/
