name: "Sapphire-Hero-Final-Build"
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # لدعم ملفاتك الكبيرة مثل sapphire-hero-rewritten.7z

      - name: Godot Android Export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
          # بما أن ملف project.godot في المجلد الرئيسي حسب صورتك
          relative_project_path: "./"
          export_preset: "Android"
          archive_output: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sapphire-Hero-Game
          path: /home/runner/.local/share/godot/archives/
